return {
  ["workshop-1595631294"]={
    configuration_options={
      BundleItems=false,
      ChangeSkin=true,
      Digornot=true,
      DragonflyChest=false,
      Icebox=false,
      SaltBox=false 
    },
    enabled=true 
  },
  ["workshop-2788995386"]={
    configuration_options={
      alterguardianhat=true,
      antlion=true,
      armor_sanity=true,
      armordragonfly=true,
      armordreadstone=true,
      armormarble=true,
      armorruins=true,
      armorskeleton=true,
      batbat=true,
      beargervest=true,
      bedroll_furry=true,
      beefalohat=true,
      berrybush=true,
      boomerang=true,
      brush=true,
      cookiecutterhat=true,
      deer_antler=true,
      deserthat=true,
      dragonflyfurnace=true,
      dreadstonehat=true,
      eyebrellahat=true,
      eyeofterror_loot=true,
      eyeturret=true,
      featherfan=true,
      friendlyfruitfly=true,
      glasscutter=true,
      goose_feather=true,
      hivehat=true,
      icepack=true,
      klaussackloot=true,
      krampus_sack=true,
      language=true,
      lureplantbulb=true,
      malbatross_beak=true,
      malbatross_feather=true,
      moonrockseed=true,
      multitool_axe_pickaxe=true,
      mushroom_light=true,
      mushroomhat=true,
      nightlight=true,
      nightstick=true,
      nightsword=true,
      orangeamulet=true,
      orangestaff=true,
      pets=true,
      premiumwateringcan=true,
      pumpkin_lantern=true,
      ruins_bat=true,
      ruinshat=true,
      saddle_basic=true,
      saddle_race=true,
      saddle_war=true,
      saltbox=true,
      saltlick=true,
      seedpouch=true,
      shadow_deconstruct=true,
      shadowheart=true,
      sisturn=true,
      skeletonhat=true,
      spiderhat=true,
      spore=true,
      staff_tornado=true,
      toadstool=true,
      townportal=true,
      townportal_travel=true,
      townportaltalisman=true,
      trident=true,
      umbrella=true,
      watermelonhat=true,
      whip=true,
      yellowamulet=true 
    },
    enabled=true 
  },
  ["workshop-478005098"]={ configuration_options={  }, enabled=true },
  ["workshop-501385076"]={
    configuration_options={
      quick_cook_on_fire=true,
      quick_harvest=true,
      quick_pick_cactus=true,
      quick_pick_plant_normal_ground=true 
    },
    enabled=true 
  },
  ["workshop-623749604"]={
    configuration_options={
      Craft="Normal",
      Destroyable="DestroyByPlayer",
      FoodSpoilage=0.5,
      Language="TCh",
      Position="Center",
      Slots=80 
    },
    enabled=true 
  },
  ["workshop-1185229307"]={
    configuration_options={
      [""]="",
      DAMAGE_NUMBERS=true,
      DAMAGE_RESISTANCE=true,
      FRAME_PHASES=true,
      HORIZONTAL_OFFSET=0,
      NOEPIC=false,
      NONOEPIC=false,
      WETNESS_METER=false 
    },
    enabled=true 
  },
  ["workshop-1207269058"]={ configuration_options={  }, enabled=true },
  ["workshop-2287303119"]={
    configuration_options={
      [""]=0,
      T_crop=true,
      chestB=-1,
      chestG=-1,
      chestR=-1,
      display_hp=1,
      food_estimation=-1,
      food_order=0,
      food_style=0,
      item_info_mod=0,
      lang="Auto",
      show_buddle_item=1,
      show_food_units=-1,
      show_uses=-1 
    },
    enabled=true 
  },
  ["workshop-347079953"]={
    configuration_options={ DFV_Language="EN", DFV_MinimalMode="default" },
    enabled=true 
  },
  ["workshop-362175979"]={ configuration_options={ ["Draw over FoW"]="disabled" }, enabled=true },
  ["workshop-374550642"]={ configuration_options={ MAXSTACKSIZE=99 }, enabled=true },
  ["workshop-375850593"]={ configuration_options={  }, enabled=true },
  ["workshop-375859599"]={
    configuration_options={
      divider=5,
      random_health_value=0,
      random_range=0,
      send_unknwon_prefabs=false,
      show_type=0,
      unknwon_prefabs=1,
      use_blacklist=true 
    },
    enabled=true 
  },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  },
  ["workshop-661253977"]={
    configuration_options={ amudiao=true, baodiao=1, kong=0, nillots=0, rendiao=2, zbdiao=true },
    enabled=true 
  } 
}
