return {
  ["workshop-1595631294"]={
    configuration_options={
      BundleItems=false,
      ChangeSkin=true,
      Digornot=true,
      DragonflyChest=false,
      Icebox=false,
      SaltBox=false 
    },
    enabled=true 
  },
  ["workshop-2788995386"]={
    configuration_options={
      alterguardianhat=true,
      antlion=false,
      armor_sanity=false,
      armordragonfly=true,
      armordreadstone=true,
      armormarble=false,
      armorruins=false,
      armorskeleton=true,
      batbat=true,
      beargervest=true,
      bedroll_furry=false,
      beefalohat=false,
      berrybush=true,
      boomerang=false,
      brush=false,
      cookiecutterhat=true,
      deer_antler=true,
      deserthat=false,
      dragonflyfurnace=true,
      dreadstonehat=true,
      eyebrellahat=true,
      eyeofterror_loot=false,
      eyeturret=true,
      featherfan=true,
      friendlyfruitfly=true,
      glasscutter=true,
      goose_feather=true,
      hivehat=true,
      icepack=true,
      klaussackloot=true,
      krampus_sack=false,
      language=true,
      lureplantbulb=false,
      malbatross_beak=true,
      malbatross_feather=true,
      moonrockseed=false,
      multitool_axe_pickaxe=true,
      mushroom_light=false,
      mushroomhat=false,
      nightlight=true,
      nightstick=false,
      nightsword=true,
      orangeamulet=false,
      orangestaff=false,
      pets=true,
      premiumwateringcan=true,
      pumpkin_lantern=true,
      ruins_bat=false,
      ruinshat=false,
      saddle_basic=false,
      saddle_race=false,
      saddle_war=false,
      saltbox=false,
      saltlick=false,
      seedpouch=false,
      shadow_deconstruct=false,
      shadowheart=true,
      sisturn=false,
      skeletonhat=true,
      spiderhat=true,
      spore=false,
      staff_tornado=true,
      toadstool=true,
      townportal=true,
      townportal_travel=true,
      townportaltalisman=false,
      trident=true,
      umbrella=true,
      watermelonhat=true,
      whip=true,
      yellowamulet=false
    },
    enabled=true
  },
  ["workshop-478005098"]={ configuration_options={  }, enabled=true },
  ["workshop-501385076"]={
    configuration_options={
      quick_cook_on_fire=true,
      quick_harvest=true,
      quick_pick_cactus=true,
      quick_pick_plant_normal_ground=true 
    },
    enabled=true 
  },
  ["workshop-623749604"]={
    configuration_options={
      Craft="Normal",
      Destroyable="DestroyByPlayer",
      FoodSpoilage=0.5,
      Language="TCh",
      Position="Center",
      Slots=80 
    },
    enabled=true 
  },
  ["workshop-1185229307"]={
    configuration_options={
      [""]="",
      DAMAGE_NUMBERS=true,
      DAMAGE_RESISTANCE=true,
      FRAME_PHASES=true,
      HORIZONTAL_OFFSET=0,
      NOEPIC=false,
      NONOEPIC=false,
      WETNESS_METER=false 
    },
    enabled=true 
  },
  ["workshop-1207269058"]={ configuration_options={  }, enabled=true },
  ["workshop-2287303119"]={
    configuration_options={
      [""]=0,
      T_crop=true,
      chestB=-1,
      chestG=-1,
      chestR=-1,
      display_hp=1,
      food_estimation=-1,
      food_order=0,
      food_style=0,
      item_info_mod=0,
      lang="Auto",
      show_buddle_item=1,
      show_food_units=-1,
      show_uses=-1 
    },
    enabled=true 
  },
  ["workshop-347079953"]={
    configuration_options={ DFV_Language="EN", DFV_MinimalMode="default" },
    enabled=true 
  },
  ["workshop-362175979"]={ configuration_options={ ["Draw over FoW"]="disabled" }, enabled=true },
  ["workshop-374550642"]={ configuration_options={ MAXSTACKSIZE=99 }, enabled=true },
  ["workshop-375850593"]={ configuration_options={  }, enabled=true },
  ["workshop-375859599"]={
    configuration_options={
      divider=5,
      random_health_value=0,
      random_range=0,
      send_unknwon_prefabs=false,
      show_type=0,
      unknwon_prefabs=1,
      use_blacklist=true 
    },
    enabled=true 
  },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  },
  ["workshop-661253977"]={
    configuration_options={ amudiao=true, baodiao=1, kong=0, nillots=0, rendiao=2, zbdiao=true },
    enabled=true 
  },
  ["workshop-1852257480"]={ configuration_options={ horizontal=0, info=true, vertical=-30 }, enabled=true },
  ["workshop-462434129"]={
    configuration_options={
      MOD_RESTART_ALLOW_KILL=true,
      MOD_RESTART_ALLOW_RESTART=true,
      MOD_RESTART_ALLOW_RESURRECT=true,
      MOD_RESTART_CD_BONUS=0,
      MOD_RESTART_CD_KILL=1,
      MOD_RESTART_CD_MAX=0,
      MOD_RESTART_CD_RESTART=2,
      MOD_RESTART_CD_RESURRECT=3,
      MOD_RESTART_FORCE_DROP_MODE=2,
      MOD_RESTART_IGNORING_ADMIN=true,
      MOD_RESTART_MAP_SAVE=1,
      MOD_RESTART_RESURRECT_HEALTH=0,
      MOD_RESTART_TRIGGER_MODE=1,
      MOD_RESTART_WELCOME_TIPS=true,
      MOD_RESTART_WELCOME_TIPS_TIME=6
    },
    enabled=true
  }
}
